###
GET http://localhost:3000/

###
GET http://localhost:3000/users

###
POST http://localhost:3000/users
Content-Type: application/json

{
	"name": "Luis",
	"email": "luis.p.z@hotmail.com",
	"password": "12345"
}